// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY8-HWg4_f3EC2GncuJsvMa3BsjiAhC8k',
    appId: '1:236486078234:android:e8d0006c8af7d64b4346a3',
    messagingSenderId: '236486078234',
    projectId: 'rootally-ai-a6ce4',
    storageBucket: 'rootally-ai-a6ce4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOGCNhmUBe6K6qq7aJGz79lC7qoiLDLk',
    appId: '1:236486078234:ios:1d4efd9957e86dcd4346a3',
    messagingSenderId: '236486078234',
    projectId: 'rootally-ai-a6ce4',
    storageBucket: 'rootally-ai-a6ce4.appspot.com',
    androidClientId: '236486078234-ihlkfhu45n4klh2d7djpkcukqe511i75.apps.googleusercontent.com',
    iosClientId: '236486078234-jse91nb22819upgacts7d34bgq4av13r.apps.googleusercontent.com',
    iosBundleId: 'com.example.therapy',
  );
}
